[package]
name = "polymesh-api"
version = "0.1.0"
edition = "2021"
authors = ["Robert G. Jakabosky <robert@polymesh.network>"]
license = "Apache-2.0"
description = "Polymesh Rust API"
keywords = ["polymesh", "blockchain", "substrate", "codegen"]
repository = "https://github.com/PolymeshAssociation/polymesh-api"
homepage = "https://github.com/PolymeshAssociation/polymesh-api"

[workspace]
members = [
	"crates/polymesh-api-codegen-macro",
	"crates/polymesh-api-codegen",
	"crates/polymesh-api-client",

	"examples/simple_transfer",
	"examples/subscribe_blocks",
	"examples/test_api",
]

[dependencies]
thiserror = "1.0"
log = "0.4"

serde_json = { version = "1.0", features = ["preserve_order", "arbitrary_precision"] }
serde = "1.0"

polymesh-api-codegen-macro = { version = "0.1", path = "crates/polymesh-api-codegen-macro", default-features = false }
polymesh-api-client = { version = "0.1", path = "crates/polymesh-api-client", default-features = false }

# substrate
sp-arithmetic = { version = "5.0", default-features = false }
codec = { version = "3", package = "parity-scale-codec", default-features = false }
lazy_static = "1.4.0"
async-trait = "0.1"
serde-big-array = "0.4.1"

[dev-dependencies]
anyhow = "1"
log = "0.4"
hex = "0.4"
dotenv = "0.15"
env_logger = "0.9"

tokio = { version = "1.19", features = ["full"] }

#sp-keyring = { version = "6.0.0", default-features = false }

[features]
default = [ "std", "serde", "v14" ]

v14 = [
	"polymesh-api-codegen-macro/v14",
	"polymesh-api-client/v14",
]

wasm = [
	"v14",
	"serde",
	"polymesh-api-codegen-macro/no_std",
	"polymesh-api-client/wasm",
]

serde = [
	"sp-arithmetic/serde",
	"polymesh-api-client/serde",
]

std = [
	"sp-arithmetic/std",
	"polymesh-api-codegen-macro/std",
	"polymesh-api-client/std",
]
