[package]
name = "polymesh-api-client"
version = "0.1.0"
edition = "2021"
authors = ["Robert G. Jakabosky <robert@polymesh.network>"]
license = "Apache-2.0"
description = "Polymesh API client core"
keywords = ["polymesh", "blockchain", "substrate", "codegen"]
repository = "https://github.com/PolymeshAssociation/polymesh-api"
homepage = "https://github.com/PolymeshAssociation/polymesh-api"

[dependencies]
thiserror = "1.0.31"
log = "0.4"
hex = "0.4"

tokio = { version = "1.19", features = ["full"] }
jsonrpsee = { version = "0.14", features = ["client"] }

serde_json = { version = "1.0", features = ["preserve_order"] }
serde = "1.0"

# substrate
sp-core = { version = "6.0", default-features = false }
sp-runtime = { version = "6.0", default-features = false }
sp-arithmetic = { version = "5.0", default-features = false }
frame-metadata = { version = "15.0.0", default-features = false }
codec = { version = "3", package = "parity-scale-codec", default-features = false }
scale-info = { version = "2", default-features = false }
lazy_static = "1.4.0"
async-trait = "0.1"
serde-big-array = "0.4.1"

[features]
default = [ "std", "serde", "v12", "v13", "v14" ]

serde = [
	"sp-core/serde",
	"sp-runtime/serde",
	"sp-arithmetic/serde",
]

v12 = ["frame-metadata/v12"]
v13 = ["frame-metadata/v13"]
v14 = ["frame-metadata/v14"]

std = [
	"frame-metadata/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-arithmetic/std",
	"scale-info/std",
]
