[package]
name = "polymesh-api-client-extras"
version = "0.3.1"
edition = "2021"
authors = ["Robert G. Jakabosky <robert@polymesh.network>"]
license = "Apache-2.0"
description = "Polymesh API client extras"
keywords = ["polymesh", "blockchain", "substrate", "codegen"]
repository = "https://github.com/PolymeshAssociation/polymesh-api"
homepage = "https://github.com/PolymeshAssociation/polymesh-api"

[dependencies]
polymesh-api = { version = "0.4", path = "../../" }

serde_json = { version = "1.0", features = ["preserve_order"] }
serde = { version = "1.0" }

# substrate
codec = { version = "3", package = "parity-scale-codec", default-features = false }
