[package]
name = "polymesh-api-codegen-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
polymesh-api-codegen = { version = "0.1", path = "../polymesh-api-codegen" }
darling = "0.14.1"
proc-macro-error = "1"
syn = "=1.0.96"
