name: Cargo Build for Ink!

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
        platform:
          - name: Wasm32 Ink!
            os: ubuntu-24.04
            target: wasm32-unknown-unknown

    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: |
            rustup update ${{ matrix.toolchain }}
            rustup default ${{ matrix.toolchain }}
            rustup target add ${{ matrix.platform.target }}
      - name: check Ink!
        run: cargo check --target ${{ matrix.platform.target }} --no-default-features --features ink,polymesh_v7 --target wasm32-unknown-unknown
