name: Cargo Build

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
        platform:
          - name: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu

          - name: Linux-i686
            os: ubuntu-20.04
            target: i686-unknown-linux-musl

          - name: Windows-x86_64-msvc
            os: windows-latest
            target: x86_64-pc-windows-msvc

          - name: MacOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: |
            rustup update ${{ matrix.toolchain }}
            rustup default ${{ matrix.toolchain }}
            rustup target add ${{ matrix.platform.target }}
      - name: check default features
        run: cargo check --target ${{ matrix.platform.target }} --verbose
      - name: check Ink!
        run: cargo check --target ${{ matrix.platform.target }} --no-default-features --features ink --target wasm32-unknown-unknown
      - name: check Wasm
        run: cargo check --target ${{ matrix.platform.target }} --no-default-features --features wasm,serde --target wasm32-unknown-unknown
